GET http://localhost:5433/productos

#####
GET http://localhost:5433/productos/6

####
GET http://localhost:5433/ventas/detalle_ventas/6

#####
POST http://localhost:5433/productos
content-type: application/json

{
    "name": "Cosa2",
    "price": 1002.0,
    "cant": 22
}

#####
PUT http://localhost:5433/productos/5
content-type: application/json

{
    "name": "CosaModificada",
    "price": 1002.0,
    "cant": 22
}
#####
DELETE http://localhost:5433/productos/rere

#####
GET http://localhost:5433/accounts
#####
POST http://localhost:5433/signup
content-type: application/json

{
    "user": "franco",
    "password": "asd123" 
}