GET http://localhost:5433/productos

#####
GET http://localhost:5433/ventas

#####
GET http://localhost:5433/ventas/empleado/2

#####
GET http://localhost:5433/productos/6

#####
GET http://localhost:5433/cuentas/1


####
GET http://localhost:5433/ventas/detalle_ventas/6

#####
POST http://localhost:5433/productos
content-type: application/json

{
    "name": "Cosa2",
    "price": 1002.0,
    "cant": 22
}

####
POST http://localhost:5433/roles
content-type: application/json

{
    "nombre": "rol de prueba"
}

####
PUT http://localhost:5433/roles/13
content-type: application/json

{
    "nombre": "rol de prueba3"
}

#####
GET http://localhost:5433/secciones

#####
GET http://localhost:5433/productos

#####
GET http://localhost:5433/roles/10/1/ 

#####
POST http://localhost:5433/empleados
content-type: application/json

{
    "fname": "Franco",
    "lname": "Grieco",
    "cuit": "20-40015526-9",
    "dni": 40015526,
    "mail": "francogriecoo@gmail.com",
    "nacimiento": "1996-12-21"
}

#####
PUT http://localhost:5433/productos/5
content-type: application/json

{
    "name": "CosaModificada",
    "price": 1002.0,
    "cant": 22
}
#####
DELETE http://localhost:5433/productos/rere
#####
DELETE http://localhost:5433/delete_account/2

#####
GET http://localhost:5433/accounts
#####
GET http://localhost:5433/login
content-type: application/json

{
    "user": "franco",
    "password": "asd123" ,
}
#####
POST http://localhost:5433/signup
content-type: application/json

{
    "user": "franco2",
    "password": "asd123" ,
    "rol": "administrador",
    "empleado_id": null
}
